version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    env_file: .env
    environment:
      DB_HOST: postgres_container
    networks:
      - cloth-shop-network

volumes:
  db_data:

networks:
  cloth-shop-network:
    external: true
